CC = gcc
CFLAGS = -Wall

all : exo1_1-2 exo1_3-5

exo1_1-2 :
	$(CC) $(CFLAGS) -o exo1_1-2 exo1_1-2.c

exo1_3-5 : 
	$(CC) $(CFLAGS) -o exo1_3-5 exo1_3-5.c

exo1_6-7 :
	$(CC) $(CFLAGS) -o exo1_6-7 exo1_6-7.c

clean :
	rm -rf exo1_1-2 exo1_3-5 exo1_6-7